config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  root 'posts#index'

  resources :posts, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :parent, polymorphic: true
  has_many :comments, as: :parent

  validates :body, :user, :parent, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, as: :parent

  validates :title, :body, :user, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts

  validates :name, :username, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Mock the logged in user.
  def current_user
    User.first
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :init_post, only: [:create]
  before_action :init_parent, only: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :parent_id, :parent_type)
  end

  def init_post
    @post = Post.find_by(id: params[:post_id])
    return render status: :not_found unless @post
  end

  def init_parent
    @parent = Object.
              const_get(comment_params[:parent_type]).
              find_by(id: comment_params[:parent_id])

    return render status: :not_found unless @parent
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).order(updated_at: :desc).all
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save!

    redirect_to @post
  end

  def show
    @post = Post.includes(comments: [:user]).find_by(id: params[:id])
    @parent = @post
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with scope: :comment,
  url: post_comments_path(post_id: post.id),
  local: true,
  class: 'd-flex align-items-start justify-content-between hidden',
  data: { role: 'comment-form', 'parent-id': parent.id, 'parent-type': parent.class.name} do |form| %>
  <div class="form-group flex-fill">
    <%= form.text_field :body, placeholder: 'Type your comment and click Add',
      class: 'form-control form-control-sm' %>
  </div>

  <%= form.text_field :parent_id, hidden: true, value: parent.id %>
  <%= form.text_field :parent_type, hidden: true, value: parent.class.name %>
  <%= form.submit 'Add', class: 'btn btn-primary btn-sm ml-3' %>
<% end %>

app/views/comments/_list.html.erb
<ul class="list-unstyled post-comments">
  <% comments.each do |comment| %>
    <li>
      <div class="comment">
        <img src="https://picsum.photos/32/32?<%= Time.now.to_f %>" class="author-thumb shadow">

        <div class="post-contents ml-3">
          <h6><%= comment.user.name %></h6>
          <p><%= comment.body %></p>

          <small>
            <a href data-role="toggle-comment-box"
              data-parent-id="<%= comment.id %>" data-parent-type="Comment">
              <%= octicon "comment" %> Comment
            </a>
          </small>

          <div class="mt-2">
            <%= render 'comments/form', parent: comment, post: @post %>
          </div>
        </div>
      </div>

      <% if comment.comments.count %>
        <%= render 'comments/list', comments: comment.comments %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyForum</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Include bootstrap for streamlined styling -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to 'MyForum', posts_path, class: 'navbar-brand' %>

        <div class="navbar">
          <ul class="navbar-nav mr-auto"></ul>
          <%= link_to 'Ask Question', new_post_path, class: 'btn btn-outline-primary my-2 my-sm-0' %>
        </div>
      </nav>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container p-3 posts-wrapper">

  <h2 class="h2 text-black-50 page-title">All Questions</h2>

  <ul class="list-unstyled posts-list">
    <% @posts.each do |post| %>
      <li class="post-item">
        <h4 class="post-title">
          <%= link_to post.title, post_path(id: post.id) %>
        </h4>
        <p class="post-body"><%= post.body %></p>

        <div class="post-footer d-flex justify-content-between">
          <small>
            <a href data-role="toggle-comment-box"
              data-parent-id="<%= post.id %>" data-parent-type="Post">
              <%= octicon "comment" %> Comment
            </a>
          </small>

          <small class="text-black-50">
            At <%= post.updated_at %> by <%= post.user.name %>
          </small>
        </div>

        <div class="mt-2">
          <%= render 'comments/form', parent: post, post: post %>
        </div>
        <hr>
      </li>
    <% end %>
  </ul>

</div>

app/views/posts/new.html.erb
<div class="container p-3">

  <%= link_to posts_path do %>
    <%= octicon "chevron-left" %> Back to All Questions
  <% end %>

  <h2 class="h2 text-black-50 page-title">Ask a question</h2>
  <p>Please specify the below details to click on the button create your question.</p>

  <%= form_with scope: :post, url: posts_path, local: true do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control' %>
    </div>
  
    <%= form.submit 'Create', class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/posts/show.html.erb
<div class="container p-3">

  <%= link_to posts_path do %>
    <%= octicon "chevron-left" %> Back to All Questions
  <% end %>

  <h2 class="h2 text-black-50 page-title">
    <%= @post.title %>
  </h2>

  <small class="post-stats text-black-50">
    At <%= @post.updated_at %> by <%= @post.user.name %>
  </small>

  <p><%= @post.body %></p>
  <%= render 'comments/list', comments: @post.comments %>

  <small>
    <a href data-role="toggle-comment-box"
      data-parent-id="<%= @post.id %>" data-parent-type="Post">
      <%= octicon "comment" %> Comment
    </a>
  </small>

  <div class="mt-2">
    <%= render 'comments/form', parent: @post, post: @post %>
  </div>

</div>